# Generated by Django 5.2.8 on 2025-11-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_categoriaingredientes_categoriaingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='refrigerado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
