# Generated by Django 5.2.8 on 2025-12-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingrredientes',
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=10)),
                ('medida', models.CharField(choices=[('l', 'litros'), ('g', 'gramos'), ('ud', 'unidades')], max_length=2)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(related_name='recetas', through='app.IngredienteReceta', to='app.ingrediente'),
        ),
    ]
