# Generated by Django 5.2.8 on 2026-01-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
